---
- hosts: ubuntu
  become: true
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: present

    - name: start service
      service:
        name: apache2
        state: started

    - name:
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        backup: yes
